In [1]:
import torch

In [42]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.rand((3, 4, 5), dtype=torch.float32)
x

tensor([[[0.2340, 0.3188, 0.4077, 0.0392, 0.8922],
         [0.4715, 0.1270, 0.0759, 0.0019, 0.0093],
         [0.6448, 0.7337, 0.3279, 0.7520, 0.8242],
         [0.0408, 0.1208, 0.6825, 0.7974, 0.5494]],

        [[0.0705, 0.8744, 0.2048, 0.9621, 0.3757],
         [0.3922, 0.3572, 0.3314, 0.0120, 0.1143],
         [0.3574, 0.1790, 0.4103, 0.9570, 0.8417],
         [0.5903, 0.6256, 0.1407, 0.3844, 0.9308]],

        [[0.5265, 0.3423, 0.8123, 0.8197, 0.6964],
         [0.5155, 0.1228, 0.0535, 0.9484, 0.2096],
         [0.2938, 0.8536, 0.0368, 0.5857, 0.7869],
         [0.0311, 0.4625, 0.2797, 0.0922, 0.3277]]])

In [43]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [44]:
# Приведите его к форме 6 X 10
torch.reshape(x, (6, 10))

tensor([[0.2340, 0.3188, 0.4077, 0.0392, 0.8922, 0.4715, 0.1270, 0.0759, 0.0019,
         0.0093],
        [0.6448, 0.7337, 0.3279, 0.7520, 0.8242, 0.0408, 0.1208, 0.6825, 0.7974,
         0.5494],
        [0.0705, 0.8744, 0.2048, 0.9621, 0.3757, 0.3922, 0.3572, 0.3314, 0.0120,
         0.1143],
        [0.3574, 0.1790, 0.4103, 0.9570, 0.8417, 0.5903, 0.6256, 0.1407, 0.3844,
         0.9308],
        [0.5265, 0.3423, 0.8123, 0.8197, 0.6964, 0.5155, 0.1228, 0.0535, 0.9484,
         0.2096],
        [0.2938, 0.8536, 0.0368, 0.5857, 0.7869, 0.0311, 0.4625, 0.2797, 0.0922,
         0.3277]])

In [45]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x * torch.LongTensor([1, 4, 2, 2, 1])

tensor([[[0.2340, 1.2752, 0.8153, 0.0784, 0.8922],
         [0.4715, 0.5082, 0.1518, 0.0038, 0.0093],
         [0.6448, 2.9349, 0.6559, 1.5039, 0.8242],
         [0.0408, 0.4832, 1.3651, 1.5948, 0.5494]],

        [[0.0705, 3.4976, 0.4097, 1.9241, 0.3757],
         [0.3922, 1.4289, 0.6627, 0.0240, 0.1143],
         [0.3574, 0.7159, 0.8207, 1.9141, 0.8417],
         [0.5903, 2.5024, 0.2814, 0.7688, 0.9308]],

        [[0.5265, 1.3690, 1.6247, 1.6395, 0.6964],
         [0.5155, 0.4911, 0.1070, 1.8968, 0.2096],
         [0.2938, 3.4142, 0.0736, 1.1714, 0.7869],
         [0.0311, 1.8500, 0.5594, 0.1843, 0.3277]]])

In [46]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.matmul(x.view(6, 10), torch.transpose(x.view(6, 10), 1, 0))

tensor([[1.3645, 1.3763, 1.0082, 1.4743, 1.4834, 1.1788],
        [1.3763, 3.7260, 2.1449, 2.9233, 2.9911, 2.4183],
        [1.0082, 2.1449, 2.2826, 2.1152, 1.8521, 1.9424],
        [1.4743, 2.9233, 2.1152, 3.7264, 2.9018, 2.1832],
        [1.4834, 2.9911, 1.8521, 2.9018, 3.4382, 1.7487],
        [1.1788, 2.4183, 1.9424, 2.1832, 1.7487, 2.1875]])

In [96]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.FloatTensor([1]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]), requires_grad = True)
y = x**3 + z -75*t
y.backward([x, z, t])

In [97]:
x.grad

tensor([3.])

In [98]:
t.grad

tensor([-75.])

In [99]:
z.grad

tensor([1.])

In [47]:
# Создайте единичный тензор размера 5x6
eye = torch.ones(5, 6)
eye

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [48]:
# Переведите его в формат numpy
import numpy as np
eye = eye.numpy()
print(type(eye))

<class 'numpy.ndarray'>


In [89]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте
from torch import nn
from torch import optim

In [100]:
x = Variable(torch.randn(1), requires_grad = False)
w1 = Variable(torch.rand(1), requires_grad=True)
y = Variable(torch.randn(1), requires_grad = False)

y = x**w1 - 2 * x**2 + 5
y.backward()

In [103]:
w = nn.Linear(1, 1, bias=False)

In [105]:
optimizer = optim.SGD([w1], lr=0.01)
criterion = nn.MSELoss()

In [106]:
optimizer.zero_grad()
pred = x**w - 2 * x**2 + 5
loss = criterion(pred, y)
print('loss: ', loss.item())

TypeError: pow() received an invalid combination of arguments - got (Linear), but expected one of:
 * (Tensor exponent)
      didn't match because some of the arguments have invalid types: (!Linear!)
 * (Number exponent)
      didn't match because some of the arguments have invalid types: (!Linear!)


In [107]:
loss.backward()

NameError: name 'loss' is not defined

In [108]:
optimizer.step()

P.S. С последним пунктом задания не успел разобраться